INSERT INTO reltabela  
  SELECT MAX(COD_TABELA)+1,'VW_EXTRATO_PREV','Relatório de Extrato Previdenciario',MAX(COD_TABELA)+1 from reltabela


-----------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_EXTRATO_PREV AS
SELECT HF.PER_PROCESSO, HF.TIP_PROCESSO, HF.COD_IDE_REL_FUNC,--HF.NUM_MATRICULA,
       (SELECT F.NOM_PESSOA_FISICA FROM TB_PESSOA_FISICA F WHERE HF.COD_IDE_CLI = F.COD_IDE_CLI) AS NOME,
       (SELECT C.NOM_CARGO         FROM TB_CARGO C         WHERE RF.COD_CARGO   = C.COD_CARGO)   AS CARGO,

       (SELECT SUM(DECODE(HFD.FLG_NATUREZA, 'C', HFD.VAL_RUBRICA, HFD.VAL_RUBRICA *-1))
          FROM TB_HFOLHA_PAGAMENTO_DET HFD
         WHERE HFD.COD_INS = 1
           AND HFD.TIP_PROCESSO  = HF.TIP_PROCESSO
           AND HFD.PER_PROCESSO  = HF.PER_PROCESSO
           AND HFD.NUM_MATRICULA = HF.NUM_MATRICULA
           AND HFD.COD_FCRUBRICA IN (SELECT CO.COD_FCRUBRICA_COMPOE FROM TB_COMPOE_DET CO
                                      WHERE CO.COD_FCRUBRICA_COMPOSTA IN (95300,95400,58200,52800,52900) -- foi adicionado INSS 09/03/2023
                                        AND CO.DAT_FIM_VIG IS NULL
                                        AND CO.COD_FCRUBRICA_COMPOE = HFD.COD_FCRUBRICA
                                   )
       )AS BASE_CONTRIBUICAO,

       (SELECT SUM(DECODE(HFD.FLG_NATUREZA, 'D', HFD.VAL_RUBRICA, HFD.VAL_RUBRICA *-1))
          FROM TB_HFOLHA_PAGAMENTO_DET HFD
         WHERE HFD.COD_INS = 1
           AND HFD.TIP_PROCESSO = HF.TIP_PROCESSO
           AND HFD.PER_PROCESSO = HF.PER_PROCESSO
           AND HFD.NUM_MATRICULA= HF.NUM_MATRICULA
           AND HFD.COD_IDE_CLI = HF.COD_IDE_CLI
           AND TRUNC (HFD.COD_FCRUBRICA/100) in (953,954,582,528,529) -- foi adicionado INSS 09/03/2023

       )AS CONTRIBUICAO_SERVIDOR,

       ROUND(((SELECT SUM(DECODE(HFD.FLG_NATUREZA, 'D', HFD.VAL_RUBRICA, HFD.VAL_RUBRICA *-1))
                 FROM TB_HFOLHA_PAGAMENTO_DET HFD
                WHERE HFD.COD_INS = 1
                  AND HFD.TIP_PROCESSO  = HF.TIP_PROCESSO
                  AND HFD.PER_PROCESSO  = HF.PER_PROCESSO
                  AND HFD.NUM_MATRICULA = HF.NUM_MATRICULA
                  AND HFD.COD_IDE_CLI   = HF.COD_IDE_CLI
                  AND TRUNC(HFD.COD_FCRUBRICA/100) IN (953,954,582,528,529) -- foi adicionado INSS 09/03/2023
              )/ -- divisão

              (SELECT (T.VAL_PER_TAXA/100) FROM TB_TAXA T
                WHERE HF.PER_PROCESSO BETWEEN T.DAT_INI_VIGENCIA
                  AND NVL(T.DAT_FIM_VIGENCIA, TO_DATE('01/12/2099'))
                  AND T.COD_PLANO     = 1
                  AND T.COD_REGIME    = 1
                  AND T.FLG_TIPO_TAXA = 'S'
              ))* --mutiplicação

              (SELECT (T.VAL_PER_TAXA/100) FROM TB_TAXA T
                WHERE HF.PER_PROCESSO BETWEEN T.DAT_INI_VIGENCIA
                  AND NVL(T.DAT_FIM_VIGENCIA, TO_DATE('01/12/2099'))
                  AND T.COD_PLANO     = 1
                  AND T.COD_REGIME    = 1
                  AND T.FLG_TIPO_TAXA = 'E'
              ),2) AS CONTRIBUICAO_PATRONAL

  FROM TB_HFOLHA_PAGAMENTO   HF,
       TB_RELACAO_FUNCIONAL RF
 WHERE HF.COD_INS = 1
   AND RF.COD_INS = 1
   AND RF.COD_IDE_CLI      = HF.COD_IDE_CLI
   AND RF.COD_ENTIDADE     = HF.COD_ENTIDADE
   AND RF.NUM_MATRICULA    = HF.NUM_MATRICULA
   AND RF.COD_IDE_REL_FUNC = HF.COD_IDE_REL_FUNC
   AND HF.TIP_PROCESSO = 'N'
  AND HF.PER_PROCESSO between to_date('01/01/2022', 'dd/mm/yyyy') and to_date('01/12/2022', 'dd/mm/yyyy')
 --   AND HF.NUM_MATRICULA = 47
   AND EXISTS ( SELECT 1 FROM TB_HFOLHA_PAGAMENTO_DET HFD1
                 WHERE HFD1.COD_INS = 1
                   AND HFD1.TIP_PROCESSO = HF.TIP_PROCESSO
                   AND HFD1.SEQ_PAGAMENTO = HF.SEQ_PAGAMENTO
                   AND HFD1.PER_PROCESSO = HF.PER_PROCESSO
                   AND HFD1.COD_IDE_CLI = HF.COD_IDE_CLI
                   AND HFD1.COD_ENTIDADE = HF.COD_ENTIDADE
                   AND HFD1.COD_IDE_REL_FUNC = HF.COD_IDE_REL_FUNC
                   AND HFD1.NUM_MATRICULA = HF.NUM_MATRICULA
                   AND TRUNC (HFD1.COD_FCRUBRICA/100) in (953,954,582,528,529) -- foi adicionado INSS 09/03/2023
    )
  ORDER BY PER_PROCESSO
;
